name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  # Backend (Rust)

  lint-backend:
    name:  Lint (fmt, clippy)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test-backend:
    name: Backend Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --release

      - name: Check all targets
        run: cargo check --all-targets

  # Frontend (Next.js)
  install-frontend:
    name: Frontend Install & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint --if-present

  build-frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    needs: install-frontend
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test --if-present
