name: Anon CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  # Backend (Rust)
  lint-backend:
    name: Backend Lint (fmt, clippy)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test-backend:
    name: Backend Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --release

      - name: Check all targets
        run: cargo check --all-targets

  # Frontend (Next.js)

  nextjs-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"

      - name: Install dependencies
        run: |
          for i in {1..3}; do
            echo "Attempt $i of 3: Installing npm dependencies..."
            if npm ci; then
              echo "npm ci succeeded on attempt $i"
              break
            else
              echo "npm ci failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "All attempts failed. Exiting."
                exit 1
              fi
              echo "Waiting before retry..."
              sleep $((i * 5))
            fi
          done
    
      - name: Lint
        run: cd client && npm run lint

      - name: Build
        run: cd client && npm run build

      - name: Cache Next.js build output
        uses: actions/cache@v4
        with:
          path: |
            ./client/.next/cache
            ./client/.next/static
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-${{ hashFiles('client/**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-

  # Anon Deployment

  deploy-anon:
    needs: [lint-backend, test-backend, nextjs-build-and-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"

      - name: Install dependencies
        run: |
          for i in {1..3}; do
            echo "Attempt $i of 3: Installing npm dependencies..."
            if npm ci; then
              echo "npm ci succeeded on attempt $i"
              break
            else
              echo "npm ci failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "All attempts failed. Exiting."
                exit 1
              fi
              echo "Waiting before retry..."
              sleep $((i * 5))
            fi
          done

      - name: Build
        run: npm run build
      