name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nextjs-build-and-test:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./client

  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
        cache-dependency-path: "./client/package-lock.json"

    - name: Install dependencies (with retry)
      run: |
        for i in {1..3}; do
          echo "Attempt $i of 3: Installing npm dependencies..."
          if npm ci; then
            echo "npm ci succeeded on attempt $i"
            break
          else
            echo "npm ci failed on attempt $i"
            if [ $i -eq 3 ]; then
              echo "All attempts failed. Exiting."
              exit 1
            fi
            echo "Waiting before retry..."
            sleep $((i * 5))
          fi
        done

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Cache Next.js build output
      uses: actions/cache@v4
      with:
        path: |
          ./client/.next/cache
          ./client/.next/static
        key: ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-${{ hashFiles('client/**.[jt]sx?') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-